name: release

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create build folder # This would actually build your project, using zip for an example artifact
        run: mkdir -p ../build
      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          tar -czvf ../build/v2-ui-linux-arm64.tar.gz ./
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: Release ${{ github.ref }}
          tag_name: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ../build/v2-ui-linux-arm64.tar.gz
          asset_name: v2-ui-linux-arm64.tar.gz
          asset_content_type: application/gzip
